name: Local
variables:
  - name: baseUrl
    value: http://localhost:5272
  - name: adminEmail
    value: admin@dainynas.lt
  - secret: true
    name: testPassword
    description: ""
  - secret: true
    name: adminToken
    description: ""
  - secret: true
    name: adminPassword
    description: ""
