name: Local
variables:
  - name: baseUrl
    value: http://localhost:8080
    description: ""
  - name: adminEmail
    value: admin@dainynas.lt
    description: ""
  - secret: true
    name: testPassword
  - secret: true
    name: adminToken
  - secret: true
    name: adminPassword
